services:
  - type: web
    name: coleta_dados
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"  # Mantém o serviço rodando o app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11

  - type: web
    name: dashboard
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "streamlit run ./dashboard.py"  # Rodando o Streamlit no serviço separado
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
